# Generated by promptkit -- do not edit. Regenerate with: promptkit update

GOBIN ?= build/bin
GO111MODULE=on
ifneq ($(OS),Windows_NT)
EXE =
else
EXE = .exe
endif
PKG = $(shell go env GOOS)_$(shell go env GOARCH)
TAGS ?=

VERSION_PKG = github.com/dmytrogajewski/spin/pkg/version
GIT_COMMIT  = $(shell git rev-parse --short HEAD 2>/dev/null || echo "none")
GIT_VERSION = $(shell git describe --tags --always --dirty 2>/dev/null || echo "dev")
BUILD_DATE  = $(shell date -u +%Y-%m-%dT%H:%M:%SZ)
LDFLAGS     = -X $(VERSION_PKG).Version=$(GIT_VERSION) -X $(VERSION_PKG).Commit=$(GIT_COMMIT) -X $(VERSION_PKG).Date=$(BUILD_DATE)
CGO_ENABLED=0

.PHONY: all
all: ${GOBIN}/spin${EXE}

# Build all binaries (alias for all)
.PHONY: build
build: all

# Show help
.PHONY: help
help:
	@echo "Available targets:"
	@echo "  all              - Build all binaries"
	@echo "  build            - Build all binaries (alias for all)"
	@echo "  install          - Install binaries to system PATH"
	@echo "  test             - Run all tests"
	@echo "  testv            - Run all tests (verbose)"
	@echo "  lint             - Run linters and deadcode analysis"
	@echo "  fmt              - Format code"
	@echo "  deadcode         - Run deadcode analysis with detailed output"
	@echo "  deadcode-why     - Show why a function is not dead (FUNC=name)"
	@echo "  clean            - Clean build artifacts"
	@echo "  bench            - Run benchmarks"

# Install binaries to user's local bin directory
install: all
	@echo "Installing binaries..."
	@mkdir -p ~/.local/bin
	@cp ${GOBIN}/spin${EXE} ~/.local/bin/
	@echo "Installed to ~/.local/bin"
	@if ! echo $$PATH | grep -q "$$HOME/.local/bin"; then \
		echo ""; \
		echo "Note: ~/.local/bin is not in your PATH"; \
		echo "Add it by running: export PATH=\"\$$HOME/.local/bin:\$$PATH\""; \
		echo "Or add the above line to your ~/.bashrc or ~/.zshrc"; \
	fi

# Run all tests
test: all
	CGO_ENABLED=0 go test ./...

# Run all tests with verbose output
testv: all
	CGO_ENABLED=0 go test ./... -v

# Run benchmarks
bench: all
	CGO_ENABLED=0 go test -run="^$$" -bench=. -benchmem ./...

# Run benchmarks with CPU profiling
benchcpu: all
	CGO_ENABLED=0 go test -run="^$$" -bench=. -benchmem -cpuprofile=cpu.prof ./...

# Run benchmarks with memory profiling
benchmem: all
	CGO_ENABLED=0 go test -run="^$$" -bench=. -benchmem -memprofile=mem.prof ./...

# Linting tools (resolve from GOPATH/bin if not on PATH)
GOPATH_BIN=$(shell go env GOPATH)/bin
GOLINT=$(or $(shell command -v golangci-lint 2>/dev/null),$(GOPATH_BIN)/golangci-lint)
DEADCODE=$(or $(shell command -v deadcode 2>/dev/null),$(GOPATH_BIN)/deadcode)

# Package paths for linting
INTERNAL_PKGS=./...
DEADCODE_PKGS=./...
LINT_GOCACHE?=/tmp/spin-go-cache
LINT_GOLANGCI_CACHE?=/tmp/spin-golangci-lint-cache

## lint: Run linters and deadcode analysis
.PHONY: lint
lint:
	@echo "Running linters..."
	@mkdir -p $(LINT_GOCACHE) $(LINT_GOLANGCI_CACHE)
	@GOCACHE=$(LINT_GOCACHE) \
	GOLANGCI_LINT_CACHE=$(LINT_GOLANGCI_CACHE) \
	CGO_ENABLED=0 $(GOLINT) run $(INTERNAL_PKGS)
	@echo "Running deadcode analysis..."
	@GOCACHE=$(LINT_GOCACHE) ./scripts/deadcode-filter.sh $(DEADCODE_PKGS)
	@echo "Linting complete"

## deadcode: Run deadcode analysis with whitelist filter (fails if dead code found)
.PHONY: deadcode
deadcode:
	@echo "Running deadcode analysis with whitelist..."
	@GOCACHE=$(LINT_GOCACHE) ./scripts/deadcode-filter.sh $(DEADCODE_PKGS)

## deadcode-json: Run deadcode analysis with JSON output
.PHONY: deadcode-json
deadcode-json:
	@echo "Running deadcode analysis (JSON output)..."
	@GOCACHE=$(LINT_GOCACHE) $(DEADCODE) -json $(DEADCODE_PKGS)

## deadcode-why: Show why a function is not dead (usage: make deadcode-why FUNC=functionName)
.PHONY: deadcode-why
deadcode-why:
	@if [ -z "$(FUNC)" ]; then \
		echo "Usage: make deadcode-why FUNC=functionName"; \
		echo "Example: make deadcode-why FUNC=bytes.Buffer.String"; \
		exit 1; \
	fi
	@echo "Analyzing why $(FUNC) is considered live..."
	@GOCACHE=$(LINT_GOCACHE) $(DEADCODE) -whylive="$(FUNC)" $(DEADCODE_PKGS)

## fmt: Format code
.PHONY: fmt
fmt:
	@echo "Formatting code..."
	@go fmt $(INTERNAL_PKGS)
	@echo "Formatting complete"

clean:
	rm -rf ${GOBIN}/
	rm -f *.prof
	rm -rf profiles/

# =============================================================================
# Binary build targets
# =============================================================================

# Always rebuild: Go's build cache handles incremental compilation efficiently.
.PHONY: ${GOBIN}/spin${EXE}
${GOBIN}/spin${EXE}:
	CGO_ENABLED=0 go build -tags "$(TAGS)" -ldflags "$(LDFLAGS)" -o ${GOBIN}/spin${EXE} ./cmd/spin

