package agent

import (
	"fmt"
	"strings"
	"sync"
	"sync/atomic"
	"time"

	"github.com/dmytrogajewski/spin/internal/security"
)

// CommandCache provides thread-safe caching of command execution results
// with TTL (time-to-live) and size-based eviction.
//
// The cache is designed to improve performance by avoiding redundant execution
// of identical read-only commands like `git status`, `ls`, etc.
//
// Features:
//   - Thread-safe using sync.Map
//   - TTL-based expiration
//   - Size-based eviction (LRU-like)
//   - Atomic size tracking
//
// Example:
//
//	cache := NewCommandCache(5*time.Second, 10*1024*1024)
//	key := cache.Key(cmd)
//	if result, ok := cache.Get(key); ok {
//	    // Use cached result
//	} else {
//	    result := executor.Execute(ctx, cmd)
//	    cache.Set(key, result)
//	}
type CommandCache struct {
	cache   sync.Map      // map[string]*cacheEntry
	ttl     time.Duration // Time-to-live for cache entries
	maxSize int64         // Maximum cache size in bytes
	size    atomic.Int64  // Current cache size
	mu      sync.Mutex    // Mutex for eviction operations
}

// cacheEntry represents a cached command result.
type cacheEntry struct {
	result    *Result
	expiresAt time.Time
	size      int64
	key       string // For eviction tracking
}

// NewCommandCache creates a new command cache with the specified TTL and max size.
//
// Parameters:
//   - ttl: Time-to-live for cache entries (e.g., 5*time.Second)
//   - maxSize: Maximum cache size in bytes (e.g., 10*1024*1024 for 10MB)
//
// Returns a configured CommandCache.
func NewCommandCache(ttl time.Duration, maxSize int) *CommandCache {
	return &CommandCache{
		ttl:     ttl,
		maxSize: int64(maxSize),
	}
}

// Get retrieves a cached result by key.
//
// Returns the cached result and true if found and not expired,
// or nil and false otherwise.
//
// Expired entries are automatically removed during Get.
func (c *CommandCache) Get(key string) (*Result, bool) {
	val, ok := c.cache.Load(key)
	if !ok {
		return nil, false
	}

	entry, ok := val.(*cacheEntry)
	if !ok {
		return nil, false
	}

	// Check expiration
	if time.Now().After(entry.expiresAt) {
		// Expired, remove from cache
		c.cache.Delete(key)
		c.size.Add(-entry.size)
		return nil, false
	}

	return entry.result, true
}

// Set stores a command result in the cache.
//
// If adding the result would exceed maxSize, older entries are evicted
// until there's enough space.
//
// Parameters:
//   - key: Cache key (typically generated by Key method)
//   - result: Command execution result to cache
func (c *CommandCache) Set(key string, result *Result) {
	// Calculate entry size
	size := int64(len(result.Stdout) + len(result.Stderr))

	// Evict if necessary
	c.mu.Lock()
	for c.size.Load()+size > c.maxSize {
		if !c.evictOldestLocked() {
			// No entries to evict
			c.mu.Unlock()
			return
		}
	}
	c.mu.Unlock()

	entry := &cacheEntry{
		result:    result,
		expiresAt: time.Now().Add(c.ttl),
		size:      size,
		key:       key,
	}

	c.cache.Store(key, entry)
	c.size.Add(size)
}

// evictOldestLocked evicts the oldest entry from the cache.
// Must be called with mu locked.
// Returns false if no entries exist to evict.
func (c *CommandCache) evictOldestLocked() bool {
	var oldestKey string
	var oldestTime time.Time
	found := false

	// Find oldest entry
	c.cache.Range(func(key, value interface{}) bool {
		entry, ok := value.(*cacheEntry)
		if !ok {
			return true
		}
		if keyStr, ok := key.(string); ok {
			if !found || entry.expiresAt.Before(oldestTime) {
				oldestKey = keyStr
				oldestTime = entry.expiresAt
				found = true
			}
		}
		return true
	})

	if !found {
		return false
	}

	// Evict oldest
	if val, ok := c.cache.LoadAndDelete(oldestKey); ok {
		if entry, ok := val.(*cacheEntry); ok {
			c.size.Add(-entry.size)
		}
		return true
	}

	return false
}

// Key generates a cache key for a command.
//
// The key is based on program, arguments, and working directory,
// ensuring that identical commands produce identical keys.
//
// Format: "program:args:dir"
func (c *CommandCache) Key(cmd *security.Command) string {
	if cmd == nil {
		return ""
	}

	var sb strings.Builder
	sb.Grow(len(cmd.Program) + len(strings.Join(cmd.Args, " ")) + len(cmd.WorkDir) + 2)
	sb.WriteString(cmd.Program)
	sb.WriteRune(':')
	sb.WriteString(strings.Join(cmd.Args, " "))
	sb.WriteRune(':')
	sb.WriteString(cmd.WorkDir)

	return sb.String()
}

// IsCacheable determines if a command result should be cached.
//
// Only read-only commands are cacheable. Write operations, destructive
// commands, and time-sensitive commands should not be cached.
//
// Cacheable commands include:
//   - Read operations: ls, cat, grep, find
//   - Git read operations: git status, git log, git diff
//   - Info commands: pwd, whoami, which
func (c *CommandCache) IsCacheable(cmd *security.Command) bool {
	if cmd == nil {
		return false
	}

	// List of cacheable programs
	cacheableCommands := map[string]bool{
		"ls":     true,
		"cat":    true,
		"grep":   true,
		"find":   true,
		"pwd":    true,
		"whoami": true,
		"which":  true,
		"git":    true, // Check args separately
		"echo":   true,
		"printf": true,
		"head":   true,
		"tail":   true,
		"wc":     true,
		"stat":   true,
		"file":   true,
		"tree":   true,
	}

	if !cacheableCommands[cmd.Program] {
		return false
	}

	// For git, only cache read operations
	if cmd.Program == "git" {
		if len(cmd.Args) == 0 {
			return false
		}

		readOnlyGitCmds := map[string]bool{
			"status":    true,
			"log":       true,
			"diff":      true,
			"show":      true,
			"branch":    true,
			"remote":    true,
			"ls-files":  true,
			"rev-parse": true,
		}

		return readOnlyGitCmds[cmd.Args[0]]
	}

	return true
}

// Clear removes all entries from the cache.
func (c *CommandCache) Clear() {
	c.cache.Range(func(key, value interface{}) bool {
		c.cache.Delete(key)
		return true
	})
	c.size.Store(0)
}

// Size returns the current cache size in bytes.
func (c *CommandCache) Size() int64 {
	return c.size.Load()
}

// Stats returns cache statistics.
type CacheStats struct {
	Size     int64 // Current size in bytes
	MaxSize  int64 // Maximum size in bytes
	Entries  int   // Number of entries
	HitRate  float64
	MissRate float64
}

// Stats returns current cache statistics.
func (c *CommandCache) Stats() CacheStats {
	entries := 0
	c.cache.Range(func(key, value interface{}) bool {
		entries++
		return true
	})

	return CacheStats{
		Size:    c.size.Load(),
		MaxSize: c.maxSize,
		Entries: entries,
	}
}

// String returns a string representation of cache stats.
func (s CacheStats) String() string {
	utilization := float64(s.Size) / float64(s.MaxSize) * 100
	return fmt.Sprintf("Cache: %d entries, %.2f%% utilized (%d/%d bytes)",
		s.Entries, utilization, s.Size, s.MaxSize)
}
