package core

import (
	"fmt"
)

// Validator classifies command safety and validates commands against security policies.
//
// The Validator provides multi-layered command classification to protect against
// malicious or unintended commands generated by AI agents. It uses pattern matching
// to classify commands into five categories: Safe, Interactive, Dangerous, Forbidden,
// and Unverified.
//
// Classification Priority:
//  1. Forbidden - Catastrophic commands (rm -rf /, fork bombs)
//  2. Dangerous - Destructive operations (rm -rf, sudo)
//  3. Interactive - Write operations (mkdir, npm install)
//  4. Safe - Read-only operations (ls, cat, git status)
//  5. Unverified - Unknown commands
//
// Thread Safety:
//
//	Validator is thread-safe and can be used concurrently.
//
// Example:
//
//	validator := NewValidator()
//	cmd, _ := ParseCommand("ls -la")
//	result, _ := validator.Classify(cmd)
//
//	if result.Classification == CommandSafe {
//	    // Execute automatically
//	}
type Validator struct {
	safePatterns        map[string][]Pattern
	interactivePatterns map[string][]Pattern
	dangerousPatterns   map[string][]Pattern
	forbiddenPatterns   []Pattern
}

// NewValidator creates a new validator with default patterns.
func NewValidator() *Validator {
	v := &Validator{
		safePatterns:        make(map[string][]Pattern),
		interactivePatterns: make(map[string][]Pattern),
		dangerousPatterns:   make(map[string][]Pattern),
		forbiddenPatterns:   []Pattern{},
	}

	v.initializeForbiddenPatterns()
	v.initializeDangerousPatterns()
	v.initializeInteractivePatterns()
	v.initializeSafePatterns()

	return v
}

// Classify determines the safety classification of a command.
//
// Classification Logic:
//  1. Check forbidden patterns first (highest priority)
//  2. Check dangerous patterns
//  3. Check interactive patterns
//  4. Check safe patterns
//  5. Return Unverified if no match
func (v *Validator) Classify(cmd *Command) (*ValidationResult, error) {
	if cmd == nil {
		return nil, ErrInvalidCommand
	}

	// Check special forbidden patterns
	if result := v.checkSpecialForbiddenPatterns(cmd); result != nil {
		return result, nil
	}

	// Check regular forbidden patterns
	if result := v.checkPatternList(cmd, v.forbiddenPatterns, CommandForbidden); result != nil {
		return result, nil
	}

	// Check dangerous patterns
	if result := v.checkPatternMap(cmd, v.dangerousPatterns, CommandDangerous); result != nil {
		return result, nil
	}

	// Check interactive patterns
	if result := v.checkPatternMap(cmd, v.interactivePatterns, CommandInteractive); result != nil {
		return result, nil
	}

	// Check safe patterns
	if result := v.checkPatternMap(cmd, v.safePatterns, CommandSafe); result != nil {
		return result, nil
	}

	// Unknown command
	return &ValidationResult{
		Classification: CommandUnverified,
		Reason:         fmt.Sprintf("no pattern matched for '%s'", cmd.Program),
		MatchedRule:    "",
		Confidence:     0.0,
	}, nil
}

// IsSafe returns true if the command is classified as safe.
func (v *Validator) IsSafe(cmd *Command) bool {
	result, err := v.Classify(cmd)
	if err != nil {
		return false
	}
	return result.Classification == CommandSafe
}

// IsInteractive returns true if the command is classified as interactive.
func (v *Validator) IsInteractive(cmd *Command) bool {
	result, err := v.Classify(cmd)
	if err != nil {
		return false
	}
	return result.Classification == CommandInteractive
}

// IsDangerous returns true if the command is classified as dangerous.
func (v *Validator) IsDangerous(cmd *Command) bool {
	result, err := v.Classify(cmd)
	if err != nil {
		return false
	}
	return result.Classification == CommandDangerous
}

// IsForbidden returns true if the command is classified as forbidden.
func (v *Validator) IsForbidden(cmd *Command) bool {
	result, err := v.Classify(cmd)
	if err != nil {
		return false
	}
	return result.Classification == CommandForbidden
}

// NeedsApproval returns true if the command needs user approval before execution.
//
// Safe commands don't need approval (auto-execute).
// Forbidden commands are blocked entirely (not approved).
// Interactive, Dangerous, and Unverified commands need approval.
func (v *Validator) NeedsApproval(cmd *Command) bool {
	result, err := v.Classify(cmd)
	if err != nil {
		return true // Err on the side of caution
	}

	// Forbidden commands shouldn't be approved, they should be blocked
	if result.Classification == CommandForbidden {
		return false
	}

	return result.Classification.NeedsApproval()
}
