package core

import (
	"errors"
	"fmt"
	"strings"
)

// Common validator errors.
var (
	ErrInvalidCommand = errors.New("invalid command")
	ErrParseError     = errors.New("command parse error")
	ErrEmptyCommand   = errors.New("empty command")
)

// CommandClass represents the safety classification of a command.
type CommandClass int

const (
	// CommandSafe - Read-only operations that can execute automatically
	CommandSafe CommandClass = iota

	// CommandInteractive - Write operations that need user approval
	CommandInteractive

	// CommandDangerous - Destructive operations requiring strong approval
	CommandDangerous

	// CommandForbidden - Commands that should never execute
	CommandForbidden

	// CommandUnverified - Unknown commands with indeterminate safety
	CommandUnverified
)

// String returns the string representation of the classification.
func (c CommandClass) String() string {
	switch c {
	case CommandSafe:
		return "safe"
	case CommandInteractive:
		return "interactive"
	case CommandDangerous:
		return "dangerous"
	case CommandForbidden:
		return "forbidden"
	case CommandUnverified:
		return "unverified"
	default:
		return "unknown"
	}
}

// NeedsApproval returns true if the command requires user approval.
//
// Safe commands don't need approval (auto-execute).
// Forbidden commands are blocked (not approved, just rejected).
// Interactive, Dangerous, and Unverified commands need approval.
func (c CommandClass) NeedsApproval() bool {
	return c == CommandInteractive || c == CommandDangerous || c == CommandUnverified
}

// Command represents a parsed shell command for validation.
type Command struct {
	// Program is the command name (e.g., "ls", "git", "rm")
	Program string

	// Args are the command arguments
	Args []string

	// Env contains environment variables
	Env map[string]string

	// WorkDir is the working directory
	WorkDir string

	// Raw is the original unparsed command string
	Raw string
}

// ValidationResult contains the result of command validation.
type ValidationResult struct {
	// Classification is the determined safety level
	Classification CommandClass

	// Reason explains why this classification was chosen
	Reason string

	// MatchedRule is the rule that matched (if any)
	MatchedRule string

	// Confidence is how confident the validator is (0.0-1.0)
	Confidence float64

	// Suggestions for safer alternatives (optional)
	Suggestions []string
}

// Pattern represents a command pattern for matching.
type Pattern struct {
	// Program is the command name
	Program string

	// ArgPatterns are patterns that must match in arguments
	ArgPatterns []string

	// ForbiddenPatterns are patterns that must NOT appear
	ForbiddenPatterns []string

	// Description explains this pattern
	Description string
}

// Validator classifies command safety and validates commands against security policies.
//
// The Validator provides multi-layered command classification to protect against
// malicious or unintended commands generated by AI agents. It uses pattern matching
// to classify commands into five categories: Safe, Interactive, Dangerous, Forbidden,
// and Unverified.
//
// Classification Priority:
//  1. Forbidden - Catastrophic commands (rm -rf /, fork bombs)
//  2. Dangerous - Destructive operations (rm -rf, sudo)
//  3. Interactive - Write operations (mkdir, npm install)
//  4. Safe - Read-only operations (ls, cat, git status)
//  5. Unverified - Unknown commands
//
// Thread Safety:
//
//	Validator is thread-safe and can be used concurrently.
//
// Example:
//
//	validator := NewValidator()
//	cmd, _ := ParseCommand("ls -la")
//	result, _ := validator.Classify(cmd)
//
//	if result.Classification == CommandSafe {
//	    // Execute automatically
//	}
type Validator struct {
	safePatterns        map[string][]Pattern
	interactivePatterns map[string][]Pattern
	dangerousPatterns   map[string][]Pattern
	forbiddenPatterns   []Pattern
}

// ParseCommand parses a command string into a Command struct.
//
// The parser handles basic shell syntax including quoted arguments
// and environment variables. Complex shell constructs like pipes,
// redirects, and command substitution are partially supported.
func ParseCommand(cmdStr string) (*Command, error) {
	cmdStr = strings.TrimSpace(cmdStr)
	if cmdStr == "" {
		return nil, ErrEmptyCommand
	}

	// Simple tokenization (space-separated)
	parts := strings.Fields(cmdStr)
	if len(parts) == 0 {
		return nil, ErrEmptyCommand
	}

	cmd := &Command{
		Program: strings.ToLower(parts[0]),
		Args:    []string{},
		Env:     make(map[string]string),
		Raw:     cmdStr,
	}

	if len(parts) > 1 {
		cmd.Args = parts[1:]
	}

	return cmd, nil
}

// NewValidator creates a new validator with default patterns.
func NewValidator() *Validator {
	v := &Validator{
		safePatterns:        make(map[string][]Pattern),
		interactivePatterns: make(map[string][]Pattern),
		dangerousPatterns:   make(map[string][]Pattern),
		forbiddenPatterns:   []Pattern{},
	}

	v.initializeForbiddenPatterns()
	v.initializeDangerousPatterns()
	v.initializeInteractivePatterns()
	v.initializeSafePatterns()

	return v
}

// initializeForbiddenPatterns sets up forbidden command patterns.
func (v *Validator) initializeForbiddenPatterns() {
	v.forbiddenPatterns = []Pattern{
		// Catastrophic deletion patterns
		{
			Program:     "rm",
			ArgPatterns: []string{"-rf", "/"},
			Description: "Attempting to delete root filesystem",
		},
		{
			Program:     "rm",
			ArgPatterns: []string{"-rf", "/*"},
			Description: "Attempting to delete root filesystem contents",
		},
		{
			Program:     "rm",
			ArgPatterns: []string{"-rf", "~"},
			Description: "Attempting to delete home directory",
		},
		{
			Program:     "rm",
			ArgPatterns: []string{"-rf", "$HOME"},
			Description: "Attempting to delete home directory",
		},
		// Fork bomb - matches the actual fork bomb syntax
		{
			Program:     ":()",
			Description: "Fork bomb detected",
		},
		// Piping to shell (common RCE vector)
		{
			Program:           "curl",
			ForbiddenPatterns: []string{"|", "bash", "sh"},
			Description:       "Piping curl output to shell",
		},
		{
			Program:           "wget",
			ForbiddenPatterns: []string{"|", "bash", "sh"},
			Description:       "Piping wget output to shell",
		},
		// Dangerous chmod
		{
			Program:     "chmod",
			ArgPatterns: []string{"-R", "777", "/"},
			Description: "Setting insecure permissions on root",
		},
		// Disk operations
		{
			Program:     "dd",
			ArgPatterns: []string{"of=/dev/sda"},
			Description: "Writing to system disk",
		},
		{
			Program:     "mkfs",
			Description: "Formatting filesystem",
		},
		// Sudo with dangerous operations
		{
			Program:     "sudo",
			ArgPatterns: []string{"rm", "-rf", "/"},
			Description: "Sudo with dangerous deletion",
		},
	}
}

// initializeDangerousPatterns sets up dangerous command patterns.
func (v *Validator) initializeDangerousPatterns() {
	// rm patterns
	v.dangerousPatterns["rm"] = []Pattern{
		{
			Program:     "rm",
			ArgPatterns: []string{"-rf"},
			Description: "Recursive force delete",
		},
		{
			Program:     "rm",
			ArgPatterns: []string{"-r"},
			Description: "Recursive delete",
		},
	}

	// rmdir
	v.dangerousPatterns["rmdir"] = []Pattern{
		{
			Program:     "rmdir",
			Description: "Remove directory",
		},
	}

	// chmod
	v.dangerousPatterns["chmod"] = []Pattern{
		{
			Program:     "chmod",
			ArgPatterns: []string{"+x"},
			Description: "Make file executable",
		},
		{
			Program:     "chmod",
			Description: "Change file permissions",
		},
	}

	// sudo - always dangerous
	v.dangerousPatterns["sudo"] = []Pattern{
		{
			Program:     "sudo",
			Description: "Execute command as root",
		},
	}

	// su
	v.dangerousPatterns["su"] = []Pattern{
		{
			Program:     "su",
			Description: "Switch user",
		},
	}

	// git dangerous operations
	v.dangerousPatterns["git"] = []Pattern{
		{
			Program:     "git",
			ArgPatterns: []string{"reset", "--hard"},
			Description: "Hard reset git repository",
		},
		{
			Program:     "git",
			ArgPatterns: []string{"push", "--force"},
			Description: "Force push to git repository",
		},
		{
			Program:     "git",
			ArgPatterns: []string{"clean", "-fd"},
			Description: "Force clean git repository",
		},
	}

	// curl with mutations
	v.dangerousPatterns["curl"] = []Pattern{
		{
			Program:     "curl",
			ArgPatterns: []string{"-X", "POST"},
			Description: "HTTP POST request",
		},
		{
			Program:     "curl",
			ArgPatterns: []string{"-X", "PUT"},
			Description: "HTTP PUT request",
		},
		{
			Program:     "curl",
			ArgPatterns: []string{"-X", "DELETE"},
			Description: "HTTP DELETE request",
		},
	}

	// wget with output
	v.dangerousPatterns["wget"] = []Pattern{
		{
			Program:     "wget",
			ArgPatterns: []string{"-O"},
			Description: "Download file with output",
		},
	}

	// Process control
	v.dangerousPatterns["kill"] = []Pattern{
		{
			Program:     "kill",
			ArgPatterns: []string{"-9"},
			Description: "Force kill process",
		},
	}

	v.dangerousPatterns["killall"] = []Pattern{
		{
			Program:     "killall",
			Description: "Kill all matching processes",
		},
	}

	v.dangerousPatterns["pkill"] = []Pattern{
		{
			Program:     "pkill",
			Description: "Kill processes by pattern",
		},
	}

	// Package managers
	v.dangerousPatterns["apt"] = []Pattern{
		{
			Program:     "apt",
			Description: "System package management",
		},
	}

	v.dangerousPatterns["yum"] = []Pattern{
		{
			Program:     "yum",
			Description: "System package management",
		},
	}

	v.dangerousPatterns["brew"] = []Pattern{
		{
			Program:     "brew",
			Description: "System package management",
		},
	}
}

// initializeInteractivePatterns sets up interactive command patterns.
func (v *Validator) initializeInteractivePatterns() {
	// File operations
	v.interactivePatterns["mkdir"] = []Pattern{
		{
			Program:     "mkdir",
			Description: "Create directory",
		},
	}

	v.interactivePatterns["touch"] = []Pattern{
		{
			Program:     "touch",
			Description: "Create or update file",
		},
	}

	v.interactivePatterns["cp"] = []Pattern{
		{
			Program:     "cp",
			Description: "Copy file",
		},
	}

	v.interactivePatterns["mv"] = []Pattern{
		{
			Program:     "mv",
			Description: "Move file",
		},
	}

	// Git write operations
	v.interactivePatterns["git"] = []Pattern{
		{
			Program:     "git",
			ArgPatterns: []string{"add"},
			Description: "Stage files in git",
		},
		{
			Program:     "git",
			ArgPatterns: []string{"commit"},
			Description: "Commit changes to git",
		},
		{
			Program:     "git",
			ArgPatterns: []string{"checkout"},
			Description: "Switch git branch",
		},
		{
			Program:     "git",
			ArgPatterns: []string{"branch"},
			Description: "Create git branch",
		},
	}

	// Package managers (user-level)
	v.interactivePatterns["npm"] = []Pattern{
		{
			Program:     "npm",
			ArgPatterns: []string{"install"},
			Description: "Install npm package",
		},
	}

	v.interactivePatterns["go"] = []Pattern{
		{
			Program:     "go",
			ArgPatterns: []string{"get"},
			Description: "Install Go package",
		},
	}

	v.interactivePatterns["pip"] = []Pattern{
		{
			Program:     "pip",
			ArgPatterns: []string{"install"},
			Description: "Install Python package",
		},
	}

	// Build tools
	v.interactivePatterns["make"] = []Pattern{
		{
			Program:     "make",
			Description: "Run makefile target",
		},
	}

	v.interactivePatterns["cargo"] = []Pattern{
		{
			Program:     "cargo",
			ArgPatterns: []string{"build"},
			Description: "Build Rust project",
		},
	}

	// Echo with redirect (write operation)
	v.interactivePatterns["echo"] = []Pattern{
		{
			Program:     "echo",
			ArgPatterns: []string{">"},
			Description: "Write to file via echo redirect",
		},
	}
}

// initializeSafePatterns sets up safe command patterns.
func (v *Validator) initializeSafePatterns() {
	// File listing and reading
	v.safePatterns["ls"] = []Pattern{
		{
			Program:     "ls",
			Description: "List files",
		},
	}

	v.safePatterns["cat"] = []Pattern{
		{
			Program:     "cat",
			Description: "Read file",
		},
	}

	v.safePatterns["head"] = []Pattern{
		{
			Program:     "head",
			Description: "Read first lines of file",
		},
	}

	v.safePatterns["tail"] = []Pattern{
		{
			Program:     "tail",
			Description: "Read last lines of file",
		},
	}

	v.safePatterns["grep"] = []Pattern{
		{
			Program:     "grep",
			Description: "Search in file",
		},
	}

	v.safePatterns["find"] = []Pattern{
		{
			Program:     "find",
			Description: "Find files",
		},
	}

	// Git read operations
	v.safePatterns["git"] = []Pattern{
		{
			Program:     "git",
			ArgPatterns: []string{"status"},
			Description: "Show git status",
		},
		{
			Program:     "git",
			ArgPatterns: []string{"log"},
			Description: "Show git log",
		},
		{
			Program:     "git",
			ArgPatterns: []string{"diff"},
			Description: "Show git diff",
		},
		{
			Program:     "git",
			ArgPatterns: []string{"show"},
			Description: "Show git commit",
		},
	}

	// System info
	v.safePatterns["pwd"] = []Pattern{
		{
			Program:     "pwd",
			Description: "Print working directory",
		},
	}

	v.safePatterns["whoami"] = []Pattern{
		{
			Program:     "whoami",
			Description: "Show current user",
		},
	}

	v.safePatterns["which"] = []Pattern{
		{
			Program:     "which",
			Description: "Find program path",
		},
	}

	v.safePatterns["date"] = []Pattern{
		{
			Program:     "date",
			Description: "Show date/time",
		},
	}

	v.safePatterns["tree"] = []Pattern{
		{
			Program:     "tree",
			Description: "Show directory tree",
		},
	}

	v.safePatterns["file"] = []Pattern{
		{
			Program:     "file",
			Description: "Determine file type",
		},
	}

	v.safePatterns["stat"] = []Pattern{
		{
			Program:     "stat",
			Description: "Show file statistics",
		},
	}

	v.safePatterns["wc"] = []Pattern{
		{
			Program:     "wc",
			Description: "Count words/lines/bytes",
		},
	}

	v.safePatterns["echo"] = []Pattern{
		{
			Program:     "echo",
			Description: "Print text",
		},
	}
}

// Classify determines the safety classification of a command.
//
// Classification Logic:
//  1. Check forbidden patterns first (highest priority)
//  2. Check dangerous patterns
//  3. Check interactive patterns
//  4. Check safe patterns
//  5. Return Unverified if no match
func (v *Validator) Classify(cmd *Command) (*ValidationResult, error) {
	if cmd == nil {
		return nil, ErrInvalidCommand
	}

	// Check special forbidden patterns
	if result := v.checkSpecialForbiddenPatterns(cmd); result != nil {
		return result, nil
	}

	// Check regular forbidden patterns
	if result := v.checkPatternList(cmd, v.forbiddenPatterns, CommandForbidden); result != nil {
		return result, nil
	}

	// Check dangerous patterns
	if result := v.checkPatternMap(cmd, v.dangerousPatterns, CommandDangerous); result != nil {
		return result, nil
	}

	// Check interactive patterns
	if result := v.checkPatternMap(cmd, v.interactivePatterns, CommandInteractive); result != nil {
		return result, nil
	}

	// Check safe patterns
	if result := v.checkPatternMap(cmd, v.safePatterns, CommandSafe); result != nil {
		return result, nil
	}

	// Unknown command
	return &ValidationResult{
		Classification: CommandUnverified,
		Reason:         fmt.Sprintf("no pattern matched for '%s'", cmd.Program),
		MatchedRule:    "",
		Confidence:     0.0,
	}, nil
}

// checkSpecialForbiddenPatterns checks for special forbidden patterns that require raw command inspection.
func (v *Validator) checkSpecialForbiddenPatterns(cmd *Command) *ValidationResult {
	// Fork bomb check
	if strings.Contains(cmd.Raw, ":(){ :|:& };:") || strings.Contains(cmd.Raw, ":()|:|&") {
		return &ValidationResult{
			Classification: CommandForbidden,
			Reason:         "Fork bomb detected",
			MatchedRule:    "fork-bomb",
			Confidence:     1.0,
		}
	}

	// Disk overwrite check
	if strings.HasPrefix(cmd.Raw, ">") && strings.Contains(cmd.Raw, "/dev/") {
		return &ValidationResult{
			Classification: CommandForbidden,
			Reason:         "Attempting to overwrite system disk",
			MatchedRule:    "disk-overwrite",
			Confidence:     1.0,
		}
	}

	// mkfs check (any filesystem)
	if strings.HasPrefix(cmd.Program, "mkfs") {
		return &ValidationResult{
			Classification: CommandForbidden,
			Reason:         "Attempting to format filesystem",
			MatchedRule:    "mkfs",
			Confidence:     1.0,
		}
	}

	return nil
}

// checkPatternList checks a list of patterns (for forbidden patterns).
func (v *Validator) checkPatternList(cmd *Command, patterns []Pattern, classification CommandClass) *ValidationResult {
	for _, pattern := range patterns {
		if v.matchesPattern(cmd, pattern) {
			return &ValidationResult{
				Classification: classification,
				Reason:         pattern.Description,
				MatchedRule:    pattern.Program,
				Confidence:     1.0,
			}
		}
	}
	return nil
}

// checkPatternMap checks a map of patterns (for dangerous/interactive/safe patterns).
func (v *Validator) checkPatternMap(cmd *Command, patternMap map[string][]Pattern, classification CommandClass) *ValidationResult {
	patterns, ok := patternMap[cmd.Program]
	if !ok {
		return nil
	}

	for _, pattern := range patterns {
		if v.matchesPattern(cmd, pattern) {
			return &ValidationResult{
				Classification: classification,
				Reason:         pattern.Description,
				MatchedRule:    pattern.Program,
				Confidence:     1.0,
			}
		}
	}
	return nil
}

// matchesPattern checks if a command matches a given pattern.
func (v *Validator) matchesPattern(cmd *Command, pattern Pattern) bool {
	// Check program name
	if cmd.Program != pattern.Program {
		return false
	}

	// Combine all args into a single string for pattern matching
	argsStr := strings.Join(cmd.Args, " ")

	// Check forbidden patterns (must be present for forbidden matches)
	if len(pattern.ForbiddenPatterns) > 0 {
		for _, forbiddenPattern := range pattern.ForbiddenPatterns {
			if strings.Contains(argsStr, forbiddenPattern) {
				return true // Matches forbidden pattern
			}
		}
		// If forbidden patterns specified but none found, no match
		return false
	}

	// Check arg patterns (all must be present)
	for _, argPattern := range pattern.ArgPatterns {
		if !strings.Contains(argsStr, argPattern) {
			return false
		}
	}

	// If no arg patterns specified, any args match
	if len(pattern.ArgPatterns) == 0 {
		return true
	}

	// All arg patterns matched
	return true
}

// IsSafe returns true if the command is classified as safe.
func (v *Validator) IsSafe(cmd *Command) bool {
	result, err := v.Classify(cmd)
	if err != nil {
		return false
	}
	return result.Classification == CommandSafe
}

// IsInteractive returns true if the command is classified as interactive.
func (v *Validator) IsInteractive(cmd *Command) bool {
	result, err := v.Classify(cmd)
	if err != nil {
		return false
	}
	return result.Classification == CommandInteractive
}

// IsDangerous returns true if the command is classified as dangerous.
func (v *Validator) IsDangerous(cmd *Command) bool {
	result, err := v.Classify(cmd)
	if err != nil {
		return false
	}
	return result.Classification == CommandDangerous
}

// IsForbidden returns true if the command is classified as forbidden.
func (v *Validator) IsForbidden(cmd *Command) bool {
	result, err := v.Classify(cmd)
	if err != nil {
		return false
	}
	return result.Classification == CommandForbidden
}

// NeedsApproval returns true if the command needs user approval before execution.
//
// Safe commands don't need approval (auto-execute).
// Forbidden commands are blocked entirely (not approved).
// Interactive, Dangerous, and Unverified commands need approval.
func (v *Validator) NeedsApproval(cmd *Command) bool {
	result, err := v.Classify(cmd)
	if err != nil {
		return true // Err on the side of caution
	}

	// Forbidden commands shouldn't be approved, they should be blocked
	if result.Classification == CommandForbidden {
		return false
	}

	return result.Classification.NeedsApproval()
}
