package llm

import (
	"bufio"
	"context"
	"encoding/json"
	"io"
	"strings"
)

// SSEEvent represents a Server-Sent Event.
type SSEEvent struct {
	Data string
	Done bool
}

// IsDone returns true if the event is a [DONE] marker.
func (e *SSEEvent) IsDone() bool {
	return e.Data == "[DONE]"
}

// SSEScanner scans Server-Sent Events from an io.Reader.
type SSEScanner struct {
	scanner *bufio.Scanner
	event   *SSEEvent
	err     error
}

// NewSSEScanner creates a new SSE scanner from an io.Reader.
//
// The scanner parses Server-Sent Events following the SSE specification:
//   - Events are separated by blank lines
//   - Each event can have multiple "data:" lines
//   - The [DONE] marker indicates end of stream
//
// Example:
//
//	scanner := NewSSEScanner(resp.Body)
//	for scanner.Scan() {
//	    event := scanner.Event()
//	    if event.IsDone() {
//	        break
//	    }
//	    fmt.Println(event.Data)
//	}
func NewSSEScanner(r io.Reader) *SSEScanner {
	return &SSEScanner{
		scanner: bufio.NewScanner(r),
	}
}

// Scan advances to the next SSE event.
// It returns false when the scan stops, either by reaching the end of the input
// or an error. After Scan returns false, the Err method will return any error
// that occurred during scanning, except that if it was io.EOF, Err will return nil.
func (s *SSEScanner) Scan() bool {
	var dataLines []string

	for s.scanner.Scan() {
		line := s.scanner.Text()

		// Empty line indicates end of event
		if line == "" {
			if len(dataLines) > 0 {
				data := strings.Join(dataLines, "\n")
				s.event = &SSEEvent{
					Data: data,
					Done: data == "[DONE]",
				}
				return true
			}
			continue
		}

		// Parse "data:" lines
		if strings.HasPrefix(line, "data: ") {
			data := strings.TrimPrefix(line, "data: ")
			dataLines = append(dataLines, data)
		}
	}

	// Check for final event without trailing blank line
	if len(dataLines) > 0 {
		data := strings.Join(dataLines, "\n")
		s.event = &SSEEvent{
			Data: data,
			Done: data == "[DONE]",
		}
		return true
	}

	s.err = s.scanner.Err()
	return false
}

// Event returns the most recent SSE event generated by a call to Scan.
func (s *SSEScanner) Event() *SSEEvent {
	return s.event
}

// Err returns the first error that was encountered by the Scanner.
func (s *SSEScanner) Err() error {
	return s.err
}

// streamResponse processes streaming SSE response and sends chunks to the channel.
//
// This function:
//   - Parses SSE events from the reader
//   - Converts JSON deltas to StreamChunk
//   - Sends chunks to the provided channel
//   - Handles context cancellation
//   - Sends error chunks on parse failures
//
// The channel is NOT closed by this function - the caller must close it.
//
// Example:
//
//	chunks := make(chan StreamChunk, 10)
//	go func() {
//	    defer close(chunks)
//	    if err := streamResponse(ctx, resp.Body, chunks); err != nil {
//	        log.Printf("stream error: %v", err)
//	    }
//	}()
func streamResponse(ctx context.Context, r io.Reader, chunks chan<- StreamChunk) error {
	scanner := NewSSEScanner(r)

	for scanner.Scan() {
		event := scanner.Event()

		// Handle [DONE] marker
		if event.IsDone() {
			select {
			case chunks <- StreamChunk{Type: ChunkTypeDone}:
			case <-ctx.Done():
				return ctx.Err()
			}
			return nil
		}

		// Parse JSON delta
		var delta chatCompletionChunk
		if err := json.Unmarshal([]byte(event.Data), &delta); err != nil {
			// Send error chunk but continue processing
			select {
			case chunks <- StreamChunk{Type: ChunkTypeError, Error: err}:
			case <-ctx.Done():
				return ctx.Err()
			}
			continue
		}

		// Convert and send chunk
		if chunk := convertDelta(&delta); chunk != nil {
			select {
			case chunks <- *chunk:
			case <-ctx.Done():
				return ctx.Err()
			}
		}
	}

	return scanner.Err()
}

// convertDelta converts a chatCompletionChunk to a StreamChunk.
//
// This function handles different types of deltas:
//   - Content deltas (text generation)
//   - Tool call deltas (function calling)
//   - Finish reason markers
//
// Returns nil if the delta is empty or has no meaningful content.
func convertDelta(delta *chatCompletionChunk) *StreamChunk {
	if len(delta.Choices) == 0 {
		return nil
	}

	choice := delta.Choices[0]
	chunk := &StreamChunk{}

	// Handle content delta
	if choice.Delta.Content != "" {
		chunk.Type = ChunkTypeContentDelta
		chunk.Content = choice.Delta.Content
		return chunk
	}

	// Handle tool call delta
	if len(choice.Delta.ToolCalls) > 0 {
		tc := choice.Delta.ToolCalls[0]
		chunk.Type = ChunkTypeToolCallDelta
		chunk.ToolCall = &ToolCall{
			ID:   tc.ID,
			Type: tc.Type,
			Function: FunctionCall{
				Name:      tc.Function.Name,
				Arguments: tc.Function.Arguments,
			},
		}
		return chunk
	}

	// Handle finish reason
	if choice.FinishReason != nil && *choice.FinishReason != "" {
		chunk.Type = ChunkTypeDone
		chunk.FinishReason = *choice.FinishReason
		return chunk
	}

	return nil
}

// chatCompletionChunk represents a streaming chunk from the chat completion API.
type chatCompletionChunk struct {
	ID      string `json:"id"`
	Choices []struct {
		Delta struct {
			Content   string `json:"content"`
			ToolCalls []struct {
				Index    int    `json:"index"`
				ID       string `json:"id"`
				Type     string `json:"type"`
				Function struct {
					Name      string `json:"name"`
					Arguments string `json:"arguments"`
				} `json:"function"`
			} `json:"tool_calls"`
		} `json:"delta"`
		FinishReason *string `json:"finish_reason"`
	} `json:"choices"`
}
